Entity\Utilisateurs:
  type: entity
  table: utilisateurs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nom:
      type: string
      length: 255
    prenom:
      type: string
      length: 255
    login:
      type: string
      length: 50
      nullable: true
    password:
      type: string
      length: 50
      nullable: true
    adresse:
      type: string
      length: 50
      nullable: true
    email:
      type: string
      length: 50
      nullable: true
    telephone:
      type: string
      nullable: true